### ISSUE TITLE
How To Setup "Network which require a HTTP Proxy"

### ISSUE THREAD

**Issue by yumin9822** [v3aqb/fwlite#39]
Could you describe how to "support Network which require a HTTP Proxy" in your HowTo? Thanks

**Comment by yumin9822** [comment]
我公司网络，访问外网所有资源只能通过一个需要认证的http代理。我现在有一个国外VPS安装了shadowsocks，希望通过你的软件实现首先通过公司的http代理去连接我这个shadowsocks服务器。苦于不知道设置，求指教！谢谢

**Comment by v3aqb** [comment]
修改 userconf.ini
[fgfwproxy]
parentproxy = http://user:pass@proxyserver

**Comment by temp321** [comment]
![o9 kgf1 0emtcg4zkb f9](https://cloud.githubusercontent.com/assets/4036801/5851027/eacfb8e2-a23a-11e4-8259-28487849473d.png)
加上了还是不行，提示
FW-Lite 13:29:26 WARNING CONNECT tools.google.com:443 via AWS failed on read from remote! remote closed

**Comment by v3aqb** [comment]
CCProxy的兼容性问题

**Comment by whiteskin** [comment]
parentproxy = http://user:pass@proxyserver

代理的用户名中有空格时报错 如john doe, 密码xxxx
ValueError: invalid literal for int() with base 10: 'doe:xxxx@lps3.amk.st.com:8080

**Comment by v3aqb** [comment]
Url里不能有空格（RFC 1738）
试试 john%20doe

whiteskin <notifications@github.com>于2015-6-2 9:35 周二写道：

parentproxy = http://user:pass@proxyserver

**Comment by whiteskin** [comment]
原来如此. solved. thx.
