### ISSUE TITLE
FW-Lite detected as DarkKomet Virus

### ISSUE THREAD

**Issue by DragonStuff** [v3aqb/fwlite#42]
https://www.virustotal.com/en/file/266498c1e92c1858850fcadd6589a87a6e505259b156a8b09356e8a6584bfe40/analysis/

**Comment by v3aqb** [comment]
I don't think anyone uses rising would ever notice this.

**Comment by DragonStuff** [comment]
My antivirus (Webroot Secureaware) and on another machine (Avast) started reporting this as malware 4 days ago.

**Comment by v3aqb** [comment]
FW_Lite.exe is a loader runs "./Python27/python27.exe -B FW_Lite.pyw", it was a AutoIt executable.
Rewrite it in cpp, should quiet those antivirus thing down now.

https://www.virustotal.com/en/file/8d4a0387511c662495bf56bf4d9e3d789638ce6c416110c81e90011cbf07b4ab/analysis/

**Comment by v3aqb** [comment]
https://www.virustotal.com/zh-cn/file/a976078b4faf1a91a3fdbec18e53cc3d4c27b979e66840e0ee2eabe42da35b07/analysis/1430901460/
