### ISSUE TITLE
你好，我使用后总是报错udp failed

### ISSUE THREAD

**Issue by tudi1909** [v3aqb/fwlite#52]
不知道如何解决，配置都是没问题的，感谢

FWLite 12:51:00 INFO CONNECT live.github.com:443 via direct
FWLite 12:51:01 INFO resolve github.map.fastly.net. via udp failed!
FWLite 12:51:03 INFO resolve googlehosted.l.googleusercontent.com. via udp failed!
FWLite 12:51:03 INFO CONNECT clients2.googleusercontent.com:443 via shadowsocks
FWLite 12:51:03 INFO resolve live.github.com via udp failed!
FWLite 12:51:06 INFO resolve kor85.czsm.pw via udp failed!
FWLite 12:51:06 WARNING CONNECT clients2.googleusercontent.com:443 via shadowsocks failed on connect! error('getaddrinfo returns an empty list',)
FWLite 12:51:06 INFO CONNECT clients2.googleusercontent.com:443 via shadowsocks

**Comment by v3aqb** [comment]
配置文件userconf.ini，填上正确的DNS试试
[dns]
localdns = isp的dns
默认是阿里公共dns，不一定好用

**Comment by tudi1909** [comment]
已经设置好，感谢指点

**Comment by v3aqb** [comment]
With new DNS cache, modify the config file is no longer needed (unless DNS server is enabled, which require a usable local DNS server).
