### ISSUE TITLE
包含鉴权信息的ftp地址没法解析

### ISSUE THREAD

**Issue by egops** [v3aqb/fwlite#53]
rt， 默认8.8.8.8的服务器有时候会导致一些网站没法登陆。提示无法解析域名。

**Comment by v3aqb** [comment]
userconf.ini

[dns]
remotedns = dns _server

遇到无法解析域名的情况，fwlite应该会认为域名被墙自动走代理的

egops <notifications@github.com>于2016年7月6日周三 15:55写道：

**Comment by egops** [comment]
额，我用的是自己的域名，挂在阿里云上。目前看来应该是包含鉴权信息的ftp地址没法解析，好像不是dns的锅。不过我把软件关了就可以解析，可能是软件问题。

**Comment by v3aqb** [comment]
HTTP proxy is not supposed to handle FTP requests anyway.

**Comment by egops** [comment]
那我只能关闭程序来使用ftp了？

**Comment by v3aqb** [comment]
用支持HTTP CONNECT的FTP客户端（被动模式），或者关闭FTP客户端的代理设置

egops <notifications@github.com>于2016年7月8日周五 14:29写道：
