### ISSUE TITLE
how to install fwlite in centos7

### ISSUE THREAD

**Issue by qrpengx** [v3aqb/fwlite#55]
how to install fwlite in centos7

AttributeError: 'module' object has no attribute 'SECP256K1'

**Comment by v3aqb** [comment]
I guess python-cryptography is outdated.

qrpengx <notifications@github.com>于2016年7月8日周五 15:38写道：

**Comment by v3aqb** [comment]
It should be compatible with older version cryptography now.

>

**Comment by v3aqb** [comment]
just updated, try with virtualenv
