### ISSUE TITLE
 界面显示不出来

### ISSUE THREAD

**Issue by sysoncloud** [v3aqb/fwlite#57]
界面显示不出来, 运行后提示:
"sni-qt/8242" WARN  08:46:30.216 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
No systemtrayicon available

我公司上网需要http代理,在此之上我想用shadowsocks, userconfig.ini到底该怎么配呢, 相关信息太少看不明白, 比如proxy1 = http://127.0.0.1:8086 是个什么东东, 还有proxy2,proxy3, 有先后顺序吗,等等

**Comment by v3aqb** [comment]
问题1：
KDE Plasma 5？升级试试
或者不用图形界面：
    python2 /path_to/fgfw-lite/fgfw-lite.py

问题2：
[fgfwproxy]
parentproxy = 公司上网的代理

[parents]
这里添加翻墙用的代理，可以添加多个，没有顺序
