### ISSUE TITLE
Incompatible with Pcap_DNSProxy (slow DNS server?)

### ISSUE THREAD

**Issue by standritsu** [v3aqb/fwlite#62]
FW_Lite:INFO FWLite 4.20.3 with gevent 1.2.2

问题的链接是api-prod.wallstreetcn.com:433

只要访问这个链接，浏览器和其它软件就没办法再连接fwlite，日志里只剩下不停在刷api-prod.wallstreetcn.com:433，需要重启才能正常访问互联网，手动reset这个链接问题解决。

**Comment by v3aqb** [comment]
fwlite 确实有的时候会停止响应，原因不明。点托盘图标里的重新载入可以解决。

刚刚发了个新版，可以试试，不过应该不会解决问题

**Comment by standritsu** [comment]
12:51:41 get_proxy:INFO api-prod.wallstreetcn.com in CN
12:51:41 8118:INFO CONNECT api-prod.wallstreetcn.com:443 via direct. 65444
12:51:53 8118:INFO CONNECT api-prod.wallstreetcn.com:443 via direct. 65443
12:52:05 8118:INFO CONNECT api-prod.wallstreetcn.com:443 via direct. 65446
12:52:16 8118:INFO CONNECT api-prod.wallstreetcn.com:443 via direct. 65447
12:52:28 8118:INFO CONNECT api-prod.wallstreetcn.com:443 via direct. 65445
12:52:28 get_proxy:INFO dashuju.wallstreetcn.com in CN
12:52:28 8118:INFO CONNECT dashuju.wallstreetcn.com:443 via direct. 65449
12:52:40 8118:INFO CONNECT api-prod.wallstreetcn.com:443 via direct. 65450


新版还是有这个问题，接下来就没了...

试试访问这里 https://wallstreetcn.com/markets?from=navbar 然后随便点开一个“更多”看看能不能重现？我这里百分百出现。

**Comment by v3aqb** [comment]
试了十几次，只有一次卡住，过几秒自动恢复。建议换个 dns 试试。

**Comment by v3aqb** [comment]
happens more with video streaming...

**Comment by standritsu** [comment]
在使用PcapDNSProxy的时候才会出现这个问题，用一般的dns不会卡死。
