### ISSUE TITLE
無法透過proxy 連上外網

### ISSUE THREAD

**Issue by yuessir** [v3aqb/fwlite#65]
下面是錯誤訊息

已設定了
[parents]
192.168.0.22 = http://userName:pwd@192.168.0.22:8080/ 99

> 10:38:39 fwlite_8118:WARNING starting server: 8118
> 10:38:39 fwlite_8119:WARNING starting server: 8119
> 10:39:16 fwlite_8118:INFO CONNECT www.google.com.tw:443 via 192.168.0.22. 49400
> 10:39:16 fwlite_8118:ERROR OSError(0, 'create tunnel via 192.168.0.22 failed!')
> 10:39:16 fwlite_8118:ERROR Traceback (most recent call last):
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 83, in handle
>     await self._handle()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 94, in _handle
>     await self.handle_one_request()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 146, in handle_one_request
>     await method()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 657, in do_CONNECT
>     await self._do_CONNECT()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 682, in _do_CONNECT
>     self.remote_reader, self.remote_writer, self.ppname = await open_connection(addr, port, self.pproxy, self.timeout, iplist, True)
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\connection.py", line 117, in open_connection
>     raise IOError(0, 'create tunnel via %s failed!' % proxy.name)
> OSError: [Errno 0] create tunnel via 192.168.0.22 failed!
> 10:39:16 fwlite_8118:INFO CONNECT www.google.com.tw:443 via 192.168.0.22. 49403
> 10:39:16 fwlite_8118:ERROR OSError(0, 'create tunnel via 192.168.0.22 failed!')
> 10:39:16 fwlite_8118:ERROR Traceback (most recent call last):
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 83, in handle
>     await self._handle()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 94, in _handle
>     await self.handle_one_request()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 146, in handle_one_request
>     await method()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 657, in do_CONNECT
>     await self._do_CONNECT()
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 682, in _do_CONNECT
>     self.remote_reader, self.remote_writer, self.ppname = await open_connection(addr, port, self.pproxy, self.timeout, iplist, True)
>   File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\connection.py", line 117, in open_connection
>     raise IOError(0, 'create tunnel via %s failed!' % proxy.name)
> OSError: [Errno 0] create tunnel via 192.168.0.22 failed!

我的環境是AD網域
client---->company proxy---->internet(some websites blocks)
proxy 擋住了許多網站
所以我想透過 @v3aqb  開發的fwlite全局代理來突破封鎖
如
client---->company proxy---->ssr -->internet(freedom)
但不知是否我使用方式錯誤還是我的網絡環境問題拋出上述錯誤
再請給予指點 謝謝

**Comment by yuessir** [comment]
@v3aqb [
![snap](https://user-images.githubusercontent.com/8326310/51722895-eec8e200-2091-11e9-833a-900f5e80a92e.PNG)
](url)
已配置
 報
11:06:56 fwlite_8118:INFO CONNECT geover-prod.do.dsp.mp.microsoft.com:443 via direct. 56429
11:06:56 fwlite_8118:ERROR AttributeError("'NoneType' object has no attribute 'proxy'",)
11:06:56 fwlite_8118:ERROR Traceback (most recent call last):
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 83, in handle
    await self._handle()
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 94, in _handle
    await self.handle_one_request()
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\base_handler.py", line 146, in handle_one_request
    await method()
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 657, in do_CONNECT
    await self._do_CONNECT()
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 682, in _do_CONNECT
    self.remote_reader, self.remote_writer, self.ppname = await open_connection(addr, port, self.pproxy, self.timeout, iplist, True)
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\connection.py", line 104, in open_connection
    remote_reader, remote_writer, _ = await open_connection(proxy.hostname, proxy.port, proxy.get_via(), timeout=timeout, tunnel=True)
  File "C:\Users\User\Downloads\fwlite-v5-beta5\fwlite5\fwlite\fwlite_cli\connection.py", line 100, in open_connection
    if not proxy.proxy:
AttributeError: 'NoneType' object has no attribute 'proxy'

**Comment by v3aqb** [comment]
确实有这个问题。新版已修复
