### ISSUE TITLE
直连出现TimeoutError

### ISSUE THREAD

**Issue by standritsu** [v3aqb/fwlite#68]
访问某些可以直连的网站，如www.gelonghui.com会出现如下错误：
resolver:WARNING resolving www.gelonghui.com failed: TimeoutError()
然后访问所有网站都会出现这样的错误，并转跳到代理，假如重启，但不去碰www.gelonghui.com，那一切正常。

**Comment by v3aqb** [comment]
It seems the default ThreadPoolExecutor maxworker number is too small.

**Comment by standritsu** [comment]
系统DNS只设一个本地DNS代理的时候就会出现这种情况，多加一个普通的DNS地址就没这个问题，即使请求还是走本地的DNS代理

**Comment by standritsu** [comment]
似乎是一个域名出现问题后，fwlite就认为DNS不可用，导致其它的域名都不能解析

**Comment by v3aqb** [comment]
fwlite 用的是asyncio自带的域名解析，默认线程池大小有限，每次解析默认超时5秒。如果反复解析同一个有问题的域名，线程池耗尽之后所有的域名都不能解析。新版加了个DNS缓存，增加了线程池的大小，应该能解决这个问题。
