### ISSUE TITLE
5.5开始无法启动

### ISSUE THREAD

**Issue by standritsu** [v3aqb/fwlite#72]
系统是win11 25211，运行fwlite后什么也没显示，任务管理器显示进程闪退了。

把5.4的cryptography拷进去能正常使用，但升级5.6后彻底不行了。

**Comment by v3aqb** [comment]
把cryptography目录删掉重新解压试试

**Comment by standritsu** [comment]
OK了，我的错

**Comment by v3aqb** [comment]
cryptography 的问题，不能覆盖升级。我应该说明一下
